language: python
sudo: required
python:
- 3.4.3
install:
- make install
script:
- make test
deploy:
  provider: heroku
  api_key:
    secure: Hdd30jsUrQyFk1rgXQUHZ98DTvL5B95lfJBJKUETstklfKTf7Ae5HOqnAa44M8ILWMp+UDQqKvl/Kli+GrJSQC9HkH4UGzerWliJEjEaulaTK8zomhRe/FH7RdHF3ooiksRsht8DUumKVXva4bM6/kZ9cPTZ/dsHLSqfw6lbKyKw9uJLw19gQ9Qa7qp+LxSPTxvXKPcrkDjL8TDaxntI7RzenPyAO4eSJKQL8u1pixQUCCQDAwAvdT+Guc1eZK82tP0L6PnuFlt8ebILO0pa4lxj47/HTsvrfbJNIlvdHdiASXWLrclEeONVnVNMEpZGqccKFT2EZNzZaaexmcrYgqoc8OCmgM922W9nYxO9Y9mo9TQ6zUtObvAjy4vmyyynKPuZdzQQKdU649S4BMffqScb/g7BVjlhR6R88oXX589a8HrXpNSlvTltnKEbym+fNk2OBr6b4PsSSJ1AMa0WnO+fTCOGSbukXj23RWECvSZC58GNbxAaNmtWJhZVXjxxw5qQWSuBpffLoURpXjqpxaTIsI+rKWkrDseW6ZZZ7SfOWoYRosI8W17aGMmx3qHZt1pvFAuNtCfnLSsoNNg1wjx4s/1DVBxK7+uBfK6/tRaUYiakSBLXClKrPG+4wmrbo1kGPtNYhN2NKs4eH1j1uV5X8Law+KGxFGKNFKZRFvc=
  app: aplicacion-bares
  
after_deploy:
- run python manage.py syncdb
